### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party.spider'

### ISSUE THREAD

**Issue by PiranavS** [RUCKBReasoning/RESDSQL#24]
Traceback (most recent call last):
  File "[/Users/piranavs/hay_test/resdsql/text2sql.py](https://file+.vscode-resource.vscode-cdn.net/Users/piranavs/hay_test/resdsql/text2sql.py)", line 16, in <module>
    from utils.spider_metric.evaluator import EvaluateTool
  File "[/Users/piranavs/hay_test/resdsql/utils/spider_metric/evaluator.py](https://file+.vscode-resource.vscode-cdn.net/Users/piranavs/hay_test/resdsql/utils/spider_metric/evaluator.py)", line 4, in <module>
    from third_party.spider.preprocess.get_tables import dump_db_json_schema
ModuleNotFoundError: No module named 'third_party.spider'

I am getting this error during inference. Am I doing something wrong?

**Comment by lihaoyang-ruc** [comment]
The error indicates that you are missing evaluation scripts. Did you clone them as we show in the README?
```
cd third_party
git clone https://github.com/ElementAI/spider.git
git clone https://github.com/ElementAI/test-suite-sql-eval.git
mv ./test-suite-sql-eval ./test_suite
cd ..
```

**Comment by PiranavS** [comment]
Yes I did, but it didn't get cloned somehow the first time around. It is working now. Thanks.
