### ISSUE TITLE
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

### ISSUE THREAD

**Issue by jiangbossB** [RUCKBReasoning/RESDSQL#47]
请问一下 label标签为什么每次只取前面四个（在prepare_batch_inputs_and_labels方法中），比如我tables.json总共设置了十张表，但是前面四个算法后的label都是0，只有后面6个label为1，经过循环之后每次只在列表中追加返回的都是前面四个label就全为0，就报了该错误，后面我调整整了tables.json中的表的顺序是可以了，后面评估schema_item_classifier又报同样的错误了？是样本不均衡的问题吗？还是说train.json中的question对应的sql查询使用的表只能在tables.json中，没有用到的就不用写进去吗？有人遇到过这样的问题吗？我是使用自己的数据集，训练集结构已经跟要求的一致。

**Comment by lihaoyang-ruc** [comment]
这个报错来自AUC指标，当输入的labels全是0或者全是1的时候，就会报这个错误。
```python
>>> from sklearn.metrics import roc_auc_score
>>> roc_auc_score([0,0,0], [0.1, 0.1, 0.2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haoyang/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 572, in roc_auc_score
    return _average_binary_score(
  File "/home/haoyang/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/haoyang/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 339, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
>>> roc_auc_score([1,1,1], [0.1, 0.1, 0.2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haoyang/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 572, in roc_auc_score
    return _average_binary_score(
  File "/home/haoyang/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/haoyang/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 339, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
>>> roc_auc_score([1,0,1], [0.1, 0.1, 0.2])
0.75
```
不过我一时想不到很好的解决办法，你可以简单地加个try except来捕捉它。

**Comment by jiangbossB** [comment]
好的。谢谢~
