### ISSUE TITLE
Cspider不加natsql训练步骤，运行到第二步的时候报错：RuntimeError: input must have 3 dimensions, got 2

### ISSUE THREAD

**Issue by exitxingling** [RUCKBReasoning/RESDSQL#49]
报错信息如下，我这边下载了xlm-roberta-large，放在base_models目录下的，下载地址：https://huggingface.co/xlm-roberta-large/tree/main
Namespace(add_fk_info=False, alpha=0.75, batch_size=4, dev_filepath='./data/preprocessed_data/preprocessed_dev_cspider_natsql.json', device='0', epochs=128, gamma=2.0, gradient_descent_step=2, learning_rate=1e-05, mode='train', model_name_or_path='./base_models/xlm-roberta-large', output_filepath='data/pre-processing/dataset_with_pred_probs.json', patience=4, save_path='./models/xlm_roberta_text2natsql_schema_item_classifier', seed=42, tensorboard_save_path='./tensorboard_log/xlm_roberta_text2natsql_schema_item_classifier', train_filepath='./data/preprocessed_data/preprocessed_train_cspider_natsql.json', use_contents=True)
Some weights of the model checkpoint at ./base_models/xlm-roberta-large were not used when initializing XLMRobertaModel: ['lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.bias']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
This is epoch 1.
Traceback (most recent call last):
  File "schema_item_classifier.py", line 463, in <module>
    _train(opt)
  File "schema_item_classifier.py", line 277, in _train
    batch_column_number_in_each_table
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/RESDSQL/utils/classifier_model.py", line 191, in forward
    batch_column_number_in_each_table
  File "/workspace/RESDSQL/utils/classifier_model.py", line 134, in table_column_cls
    output_t, (hidden_state_t, cell_state_t) = self.table_name_bilstm(table_name_embeddings)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 677, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 620, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 203, in check_input
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 2

**Comment by lihaoyang-ruc** [comment]
这看起来像是torch版本的问题，请按照我们提供的环境配置conda。

**Comment by lihaoyang-ruc** [comment]
Cspider+NatSQL的训练不会报错吗？

**Comment by exitxingling** [comment]
> 

是torch版本太低了导致的，已解决，感谢
