### ISSUE TITLE
XLM-ROBERTA-LARGE做分类的模型如何多卡运行？

### ISSUE THREAD

**Issue by exitxingling** [RUCKBReasoning/RESDSQL#52]
试着尝试了一下多卡运行，
model = nn.DataParallel(model, device_ids=devices)
model.to(device)
结果会报bug，
Traceback (most recent call last):
  File "schema_item_classifier_gpus.py", line 470, in <module>
    _train(opt)
  File "schema_item_classifier_gpus.py", line 287, in _train
    loss = encoder_loss_func.compute_loss(
  File "/workspace/RESDSQL/utils/classifier_loss.py", line 60, in compute_loss
    table_loss = self.compute_batch_loss(batch_table_name_cls_logits, batch_table_labels, batch_size)
  File "/workspace/RESDSQL/utils/classifier_loss.py", line 47, in compute_batch_loss
    loss += self.focal_loss(logits, labels)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/RESDSQL/utils/classifier_loss.py", line 16, in forward
    assert input_tensor.shape[0] == target_tensor.shape[0]
是由于这个分类模型的结构设计，无法实现多卡运行吗？

**Comment by lihaoyang-ruc** [comment]
我没尝试过多卡运行，因此目前不清楚是否是模型结构设计带来的问题。

不过他目前在单卡上运行的很好，你可以暂时在单卡上运行它。
